### ISSUE TITLE
to_aas4wrf needed?

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/eixport#10]
vein::emis_wrf is a function that produces an data-frame formatted to input AS4WRF pre-processorfor WRF-Chem. This functions could be integrated into eixport as to_as4wrf. Reasons:

eixport and EmissV functions creates emissions inputs for WRF-Chem for the with the same size as the domain of the wrfinput.
aas4wrf assigns an emissions grid into the domain.
eixport and EmissV needs solely the wrfinput. Hence, can run in any OS.
aas4wrf needs wrfinput and ncl installed and configurated.

This means that both set of functions achieve the same objective with different approaches. Therefore, both should be here to provide flexibility to the user.

The references of eixport and EmissV are in development.
The reference of aas4wrf is: 
Vara-Vela, A., Andrade, M. F., Kumar, P., Ynoue, R. Y., & Muñoz, A. G. (2016). Impact of vehicular emissions on the formation of fine particles in the Sao Paulo Metropolitan Area: a numerical study with the WRF-Chem model. Atmospheric Chemistry and Physics, 16(2), 777-797.

What do you think @Schuch666 ?

**Comment by ibarraespinosa** [comment]
Neste caso, a função tem que ser baseada em vein::emis_wrf e tambem na EmissV::stritDist, de forma que usar classes sp ou sf.

**Comment by Schuch666** [comment]
Acho que essa função pode ficar (como uma outra opção mas considerada obsoleta).

Acho que uma função no eixport deveria fazer essa transcrição do vein para o wrf

**Comment by ibarraespinosa** [comment]
Certo, claro, a verdade poderia mas não precisa. Nesse caso vou fechar o issue.

Obrigado, é bom compartilhar as ideias!

**Comment by ibarraespinosa** [comment]
Estava pensando e concordo contigo.  Vou incluir to_ass4wrf considerado mas como uma alternativa a  to_wrf o wrf_put. Abs
