### ISSUE TITLE
Suggested edits from Hollister review for JOSS

### ISSUE THREAD

**Issue by jhollist** [atmoschem/eixport#22]
- [x] R Dependency to 3.3.0
- [x] Check on Authorship - Different author list on paper vs. software.
- [x] Fix example on `emis_opt`
- [x] Check example on `wrf_plot` to make sure the warning is not a problem
- [x] Add a separate section to README for installation instructions.  A good example is https://github.com/ropensci/lawn
- [x] Add tests.  Should have coverage for at least the main functions.
- [x] Add details on how to contribute in a CONTRIBUTING.md
- [x] Provide better justification for the package. In particular, provide more detail on why an R package is needed on top of the already available lower level implementation in Fortran and C.
- [x] Add DOIs to references.
- [x] Review [PR #21](https://github.com/atmoschem/eixport/pull/21) for suggested edits
- [ ] As a future enhancement, add a vignette showing typical use case

**Comment by ibarraespinosa** [comment]
Dear @jhollist, with the our last [commit ](https://github.com/atmoschem/eixport/commit/badd00bf16af791105efcd4b4dad720cfe0493c3) we added coverage of 89%. It was not easy because but I resolved to add a file in inst/extdata for comparisons.

Please, let us know what do you think.

Best, Sergio

**Comment by leeper** [comment]
Great! @jhollist Let me know what you think over on the review issue: https://github.com/openjournals/joss-reviews/issues/607

**Comment by jhollist** [comment]
See comments on openjournals/joss-reviews#607, but the gist is 👍

**Comment by ibarraespinosa** [comment]
Thanks @leeper  and @jhollist.
https://github.com/openjournals/joss-reviews/issues/607
