### ISSUE TITLE
 "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" or 4326?

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/eixport#26]
Então Daniel, tenho uma duvida, que tentei resolver [aqui](https://earthscience.stackexchange.com/questions/13943/wrf-epsg-code-or-spatial-reference-for-lambert-conformal-mercator-and-polar-st?noredirect=1#comment26439_13943) sem muito éxito:

According to the WRF Manual , page 3-10: "As a general guideline,

- the **polar stereographic** projection is best suited for high-latitude WRF domains,
- the **Lambert conformal** projection is well suited for mid-latitude domains, and
- the **Mercator projection** is good for low-latitude domains or domains with predominantly west-east extent."

![captura de tela de 2018-06-14 00-21-37](https://user-images.githubusercontent.com/27447280/41389756-ed23f91a-6f68-11e8-961e-6ba901913c54.png)

Qual é o Sistema de Referencia exacto para cada um? Eu to achando que assumir  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs" or 4326 para cada um dos casos é um erro.

**Comment by Schuch666** [comment]
Não sei se a diferença seria muito grande, já vi (não lembro onde foi) essas projeções usadas para o caso do WRF, por enquanto esse é só um default para essas funções

Essa não é bem minha praia, talvez o @beneduzi saiba mais sobre essas projeções do WRF :)

**Comment by beneduzi** [comment]
Não sei muito sobre isso não. Mas posso tentar ajudar, a ideia classica, cada tipo de projeção insere uma deformação, mercator deforma muito os polos, hiperextimando suas areas, lambert preserva a area dentro de um para de latitudes definido. Mas efetivamente, se nao estiver modelando nada acima do circulo polar, utilize lambert. Se estiver modelando algo de meso escala, lambert quando centralizada proxima ao equador, e em grandes ares é virtualmente igual a mercator, então tambem nao precisa mudar. 
  Eu evitaria o uso de projeções cilindricas, por serem pouco usuais mesmo. 
  Na hora de plotar, a maior parte das bibliotecas de mapa permite alterar a projeção, eu particurlamente sou fã de utilizar projeçoes geodais, e normalmente aceitam uma flag para o codigo epsg. 
 Confiram esse site com lista de projeçoes por região. (para a região do Brasil, o oficial é 4326)
http://spatialreference.org/ref/epsg/

**Comment by ibarraespinosa** [comment]
Es lo mismo
http://spatialreference.org/ref/epsg/4326/proj4/
