### ISSUE TITLE
speed up wrf_create

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/eixport#34]

**Comment by Schuch666** [comment]
wrf_create is not a particularly slow function in general, but can take a minute or more depending on the number of times (frames_per_auxinput5) and number of emission species

There is two ways to speed up this process:
- reduce the number of times on the file
- reduce the number of variables (WRF ignores the missing variables), I recommend to create the emission without the unused variables using a subset of the emiss_opt variables of the WRF option

**Comment by ibarraespinosa** [comment]
Yeah, but line 99 has de for. So maybe, using a applay* could speed up this process. I will make some tests.

Another approach is parallelize code with `doMC`

This means that we have 4 approaches.

**Comment by Schuch666** [comment]
Yes indeed, but reduce the _number of times_ or _reduce the number of variables_ need just the change on the function call

In the line 99 the loop are for multiple files, maybe doMC can make some work here (but its add more one dependence to the package)

A god place to start the 'apply type' functions are the following loops, that declare the NECTDF variables
# GAS phase emissions
# AEROSOL emissions

I recommend caution with a possible 'parallel file writing' on the following loops
# GASES initialization with zeros
# AEROSOLS initialization with zeros

PS: You don't need to create new files for different scenarios (same period, domain and chem options), can just check if the emission already exists
