### ISSUE TITLE
Missing https

### ISSUE THREAD

**Issue by Schuch666** [atmoschem/eixport#46]
I found some errors in the form of 

downloading BC from the TNR_Other sector (v432_AP and .nc for 2012)
```
Error in `$<-.data.frame`(`*tmp*`, "links", value = NA) :
  replacement has 1 row, data has 0
Calls: get_edgar -> $<- -> $<-.data.frame
Execution halted

```
downloading SO2 from the SWD_INC sector (v432_AP and .nc for 2012)
```
Error in `$<-.data.frame`(`*tmp*`, "links", value = NA) :
  replacement has 1 row, data has 0
Calls: get_edgar -> $<- -> $<-.data.frame
Execution halted
```

**Comment by ibarraespinosa** [comment]
https://github.com/atmoschem/eixport/commit/a3a0540b6e39ed591b5c847caa765d76da9f5094
