### ISSUE TITLE
Different download paths

### ISSUE THREAD

**Issue by Schuch666** [atmoschem/eixport#47]
I found that some files has different patterns depending on the combination of sector and pollutant like:

downloading BC from NFE sector (v432_AP and .nc for 2012)
do get_edgar:'https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v432_AP/BC/NFE/v432_BC_2012_IPCC_2C3_2C4_2C5.0.1x0.1.zip'
do site:     'https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v432_AP/BC/NFE/v432_NFE_BC_2012_IPCC_2C3_2C4_2C5.0.1x0.1.zip'

downloading BC from TNR_Aviation_LTO sector (v432_AP and .nc for 2012)
do get_edgar:'https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v432_AP/BC/TNR_Aviation_LTO/v432_BC_2012_IPCC_1A3a_CRS.0.1x0.1.zip'
do site:     'https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v432_AP/BC/TNR_Aviation_LTO/v432_BC_2012_IPCC_1A3a_LTO.0.1x.01.zip'

downloading voc1 from the TRF sector (v432_AP and .nc for 2012)
do get_edgar: https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v432_VOC_spec/voc1/TRF/v432_VOC_spec_voc1_2012_IPCC_1A1c_1A5b1_1B1b_1B2a6_1B2b5_2C1b.zip
so site:      https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/EDGAR/datasets/v432_VOC_spec/voc1/TRF/v432_VOC_spec_voc1_2012_1A1c_1A5b1_1B1b_1B2a6_1B2b5_2C1b.0.1x0.1.zip

I also found some problems downloading the:
'NFE','TNR_Aviation_LTO','TNR_Other' sectors and the 'CO2' variable of the v432_AP dataset
and on the 
'TRF' 'TNR_Aviation_LTO' sectors from the v432_VOC_spec dataset

**Comment by ibarraespinosa** [comment]
All of this is v432_AP

**Comment by ibarraespinosa** [comment]
@Schuch666 ae, agora tu pode testar v432_AP. Agora vou continuar com VOC_spec
