### ISSUE TITLE
add gains

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/eixport#50]
https://www.iiasa.ac.at/web/home/research/researchPrograms/air/ECLIPSEv5a.html

**Comment by Schuch666** [comment]
As emissões do site do IIASA estão em total (Tg yr-1), um dataset mais útil seria o flux (o formato que o EmissV e outros preprocessadores usam para criar as emissões) são as que estão no site do ECCAD:
https://eccad3.sedoo.fr/
Teria que pegar o link da opção flux (kg m-2 s-1) mas também tem o total (Tg yr-1)

**Comment by ibarraespinosa** [comment]
boa, mas pode ter a opção de os dois formatos

**Comment by Schuch666** [comment]
sim, tem vários outros datasets nesse site do eccad (pode ser uma ideia incluir também no futuro)

**Comment by ibarraespinosa** [comment]
Do we need to provide support to external Emissions Inventories such as EDGAR and GAINS?

**Comment by Schuch666** [comment]
I think we don't need to provide support for each data-set (each data-set is different and there is a long list of datasets)

If there is a need of use of EDGAR, GAINS or another you can use (or import) the functions from EmissV, check the supported formats using:
EmissV::read()
