### ISSUE TITLE
add wrf_times

### ISSUE THREAD

**Issue by ibarraespinosa** [atmoschem/eixport#51]
Danie,tu poderia adicionar uma fun;cao para extraer uma serie de tempo POSIXct de um wrfinput ou wrfout por favor??

`wrf_times <- function(x, ...)
`

obrigado

**Comment by Schuch666** [comment]
Olá, posso sim

Por enquanto dá para extrair uma string dos tempos com wrf_get(file,"Times"), posso fazer com que a saída dessa função retorne um POSIXct e wrf_put entenda um POSIXct por compatibilidade.

Já tinha pensado em fazer isso mas nunca foi prioridade por não ter encontrado utilidade até agora

**Comment by ibarraespinosa** [comment]
entao,

Times so retorna o primeiro tempo, mas seia legal se ele retornasse a
sequancia de tempos,  emPOSIXct
Abs
[image: photo]
*Sergio Ibarra Espinosa*
Postdoc, PhD. in Atmospheric Sciences, MSc Environment, Engineer, Universidade
de São Paulo & Chinese Academy of Sciences

+ 8617643016295 <++8617643016295> | +55 11 974 253 791 <+55+11+974+253+791>
| sergio.ibarra@usp.br

www.sergioibarra.blogspot.com | Skype: sergio_ibarra1
<#SignatureSanitizer_SafeHtmlFilter_>
Rua do Matão, 1226 - Cidade Universitária São Paulo-SP - Brasil - 05508-090
<http://github.com/ibarraespinosa> <http://us.linkedin.com/in/sibarra>
<http://wiseintro.co/sergioibarra> <http://blogger.com/profile/sergioibarra>
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

ᐧ

Em seg., 25 de nov. de 2019 às 22:45, Daniel Schuch <
notifications@github.com> escreveu:

**Comment by Schuch666** [comment]
Vou fazer assim que sobrar um tempo

PS: tem certeza que o arquivo tinha mais que um tempo quando testou o wrf_get? aqui funcionou

**Comment by Schuch666** [comment]
feito!

agora wrf_get e wrf_put funcionam também com POSIXlt, só olhar na documentação e testar

**Comment by ibarraespinosa** [comment]
📣🔔🎸📈📢
[image: photo]
*Sergio Ibarra Espinosa*
Postdoc, PhD. in Atmospheric Sciences, MSc Environment, Engineer, Universidade
de São Paulo & Chinese Academy of Sciences

+ 8617643016295 <++8617643016295> | +55 11 974 253 791 <+55+11+974+253+791>
| sergio.ibarra@usp.br

www.sergioibarra.blogspot.com | Skype: sergio_ibarra1
<#SignatureSanitizer_SafeHtmlFilter_>
Rua do Matão, 1226 - Cidade Universitária São Paulo-SP - Brasil - 05508-090
<http://github.com/ibarraespinosa> <http://us.linkedin.com/in/sibarra>
<http://wiseintro.co/sergioibarra> <http://blogger.com/profile/sergioibarra>
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>


Em qui., 28 de nov. de 2019 às 17:37, Daniel Schuch <
notifications@github.com> escreveu:
